stages:
  - jest-tests
  - selenium-tests
  - backend-tests
  - postman-tests
  - validate

jest:
  stage: jest-tests
  image: node:latest
  script:
    - cd react-front-end
    - npm install
    - npm test

selenium:
  stage: selenium-tests
  image: python:latest
  services:
    - selenium/standalone-chrome:latest
  script:
    - cd react-front-end/selenium_tests
    - python acceptance_tests.py

backend:
  stage: backend-tests
  image: python:latest
  script:
    - cd back-end/tests
    - pip install requests
    - python api_tests.py

postman:
  stage: postman-tests
  image: node:latest
  script:
    - npm install -g newman
    - newman run "SeniorUplift_RESTful_API.postman_collection.json"

validate_html:
  image: node:latest
  stage: validate
  before_script:
    - npm install -g htmlhint  # Install HTML validation tool globally
  script:
    - htmlhint front-end/*.html  # Validate all HTML files in the front-end directory
  only:
    - main 